import { StyleSheet } from "react-native";
import { get } from "react-native/Libraries/TurboModule/TurboModuleRegistry";
import {
  fontEq,
  getHeightEquivalent,
  getWidthEquivalent,
} from "../../Helpers/Utilities/Utilities";
import { height, width } from "../../Helpers/Constants/AppConstants";
export const HomeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  productContainer: {
    height: height - 100,
    width: width,
  },
  carrotLogo: {
    marginTop: getHeightEquivalent(58.29),
    height: getHeightEquivalent(30.8),
    width: getWidthEquivalent(26.48),
    alignSelf: "center",
  },
  locationContainer: {
    height: getHeightEquivalent(22.69),
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: getHeightEquivalent(7.6),
  },
  locationIcon: {
    height: getHeightEquivalent(18.17),
    width: getWidthEquivalent(15.13),
    marginRight: getWidthEquivalent(5),
  },
  locationText: {
    fontSize: fontEq(18),
    fontFamily: "Gilroy-SemiBold",
    color: "#4C4F4D",
  },
  searchContainer: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    marginTop: getHeightEquivalent(12),
    height: getHeightEquivalent(50),
    width: getWidthEquivalent(343),
    backgroundColor: "#F2F3F2",
    borderRadius: 15,
    paddingHorizontal: getWidthEquivalent(15),
    marginBottom: getHeightEquivalent(15),
  },
  searchIcon: {
    height: getHeightEquivalent(18.21),
    width: getHeightEquivalent(18.21),
  },
  searchInput: {
    alignItems: "center",
    height: getHeightEquivalent(50),
    width: getWidthEquivalent(280),
    fontSize: fontEq(14),
    fontFamily: "Gilroy-SemiBold",
    color: "#7C7C7C",
    marginLeft: getWidthEquivalent(9.81),
  },
  carouselContainer: {
    height: getHeightEquivalent(114.99),
    width: getWidthEquivalent(368),
    borderWidth: 1,
    borderColor: "red",
    alignSelf: "center",
  },
  divisionContainer: {
    height: getHeightEquivalent(29),
    width: getWidthEquivalent(368),
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: getHeightEquivalent(20),
    marginTop: getHeightEquivalent(30),
    alignSelf: "center",
  },
  divisionText1: {
    fontSize: fontEq(24),
    fontFamily: "Gilroy-SemiBold",
    color: "#181725",
    alignSelf: "center",
  },
  divisionText2: {
    fontSize: fontEq(16),
    fontFamily: "Gilroy-SemiBold",
    color: "#53B175",
  },

  productList: {
    height: getHeightEquivalent(250),
    width: "100%",
    alignSelf: "center",
  },
  productCard: {
    height: getHeightEquivalent(248.51),
    width: getWidthEquivalent(173.32),
    // alignItems: "center",
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E2E2E2",
    marginRight: getWidthEquivalent(15),
    paddingHorizontal: getWidthEquivalent(15),
    paddingVertical: getHeightEquivalent(15),
  },
  productImage: {
    height: getHeightEquivalent(120),
    width: getWidthEquivalent(120),
    alignSelf: "center",
  },
  productNameText: {
    fontSize: fontEq(16),
    fontFamily: "Gilroy-Bold",
    color: "#181725",
    alignSelf: "flex-start",
    textAlign: "left",
    //marginTop: getHeightEquivalent(30),
  },
  productDescriptionText: {
    fontSize: fontEq(14),
    fontFamily: "Gilroy-Medium",
    color: "#7C7C7C",
    marginTop: getHeightEquivalent(5),
    alignSelf: "flex-start",
    textAlign: "left",
  },
  productPriceText: {
    position: "absolute",
    fontSize: fontEq(18),
    fontFamily: "Gilroy-SemiBold",
    color: "#181725",
    marginTop: getHeightEquivalent(204.64),
    alignSelf: "flex-start",
    textAlign: "left",
    marginLeft: getWidthEquivalent(15),
  },
  addToCartContainer: {
    position: "absolute",
    height: getHeightEquivalent(45.67),
    width: getHeightEquivalent(45.67),
    borderRadius: 17,
    backgroundColor: "#53B175",
    alignItems: "center",
    justifyContent: "center",
    marginTop: getHeightEquivalent(187.84),
    marginLeft: getWidthEquivalent(113.66),
  },
});
